import streamlit as st
from main import query_system
import os

# Page Config must be the first Streamlit command
st.set_page_config(
    page_title="RAG Assistant (YandexGPT)",
    page_icon="🤖",
    layout="centered"
)

# Initialize Session State for Chat History
if "messages" not in st.session_state:
    st.session_state.messages = []

from dotenv import load_dotenv
load_dotenv()

# Verify API Keys
if not os.getenv("YC_API_KEY") or not os.getenv("YC_FOLDER_ID"):
    st.error("⚠️ Yandex Cloud API keys missing! Please ensure YC_API_KEY and YC_FOLDER_ID are set in your .env file.")
    st.stop()

st.title("📚 Intelligent RAG Assistant")
st.markdown("Ask anything about your loaded documents (like *Progress and Poverty*). The answers are generated by **YandexGPT** based exclusively on the retrieved context.")

# Display Chat History
for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        st.markdown(message["content"])
        if "contexts" in message and message["contexts"]:
            with st.expander("View Source Contexts"):
                for idx, ctx in enumerate(message["contexts"]):
                    st.markdown(f"**Source {idx + 1}:**\n```text\n{ctx}\n```")

# Chat Input
if prompt := st.chat_input("Ask a question..."):
    # Add user message to state and display
    st.session_state.messages.append({"role": "user", "content": prompt})
    with st.chat_message("user"):
        st.markdown(prompt)

    # Generate and display assistant response
    with st.chat_message("assistant"):
        message_placeholder = st.empty()
        message_placeholder.markdown("Generating answer...")
        
        try:
            # Query the RAG system
            answer, contexts = query_system(prompt)
            
            # Display answer
            message_placeholder.markdown(answer)
            
            # Display context in an expander
            if contexts:
                with st.expander("View Source Contexts"):
                    for idx, ctx in enumerate(contexts):
                        st.markdown(f"**Source {idx + 1}:**\n```text\n{ctx}\n```")
                        
            # Save to history
            st.session_state.messages.append({"role": "assistant", "content": answer, "contexts": contexts})
            
        except Exception as e:
            error_msg = f"An error occurred: {str(e)}"
            message_placeholder.error(error_msg)
            import traceback
            traceback.print_exc()
